# ============================================
# СЕТЬ
# ============================================
listen_addresses = '*'
port = 5432
max_connections = 50

# ============================================
# РЕЖИМ РАБОТЫ РЕПЛИКИ
# ============================================
hot_standby = on
hot_standby_feedback = on
max_standby_archive_delay = 30s
max_wal_senders = 20
max_standby_streaming_delay = 30s
recovery_target_timeline = 'latest'

# ============================================
# ЛОГИРОВАНИЕ
# ============================================
log_connections = on
log_disconnections = on
log_recovery_conflict_waits = on